version: "3"

services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=posts
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
